<!DOCTYPE document [
        <!ELEMENT document (date|title|author|tags_set|categories_set|text)*>
        <!ELEMENT date (#PCDATA)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT author (#PCDATA)>
        <!ELEMENT tags_set (tag)*>
        <!ELEMENT tag (#PCDATA)>
        <!ELEMENT categories_set (category)*>
        <!ELEMENT category (#PCDATA)>
        <!ELEMENT text (#PCDATA)>
        ]>
<document>
	<date>2015-01-06</date>
        <title>[Legen&#8230; Dary !] Le site Internet Archive propose d&#233;sormais 2400 jeux MS-DOS gratuitement !</title>
        <author>Henri</author>
        <tags_set>
                <tag>MS-DOS</tag>
                <tag>PC</tag>
                <tag>Retro-gaming</tag>
                <tag>The Internet Archive</tag>
        </tags_set>
        <categories_set>
                <category>Bon plan</category>
        </categories_set>
        <text>
                                                                                                 
         
                 Vous aimez le r&#233;tro-gaming, et vous voulez (re)d&#233;couvrir les plus grands jeux de la fin des ann&#233;es 80 ? Il existe un endroit pour vous. 
 
 more 
 Le site  Internet Archive  entend bien sauvegarder le patrimoine li&#233; au d&#233;but du web. Musique, vid&#233;o, textes, mais aussi jeux vid&#233;o ! Et les plus nostalgiques d&#8217;entre nous devraient se r&#233;jouir puisque 2400 jeux MS-DOS sont d&#233;sormais disponibles gratuitement via une version web de l&#8217;&#233;mulateur DOSBox. Il rejoigne  la premi&#232;re fourn&#233;e  de jeux d&#8217;arcade disponibles depuis novembre. Vous pourrez donc vous y adonner directement depuis votre navigateur.. 
 
 &#192; vous les  Bust-A-Move ,  Street Fighter  et autre Wolfenstein 3D. Les papys gamers vont enfin pouvoir montrer aux jeunes de quel bois ils se chauffaient sur Atari ! 
         
 
                                                                                                         
                                                                                                                                                                                                 
        </text>
</document>
